name: aps_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: any
  material_symbols_icons: any

  cupertino_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

flutter:
  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf

  uses-material-design: true



